title: Cartographer Firmware Updater
description: Documentation for Using the Cartographer Firmware Updater Script
theme: just-the-docs
color_scheme: dark
url: https://krautech.github.io

aux_links:
  Cartographer: https://cartographer3d.com

callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: blue
  warning:
    title: Warning
    color: red
    
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
